# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'npm'
      - name: Assume AWS IAM Role
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::176218606710:role/GithubActionsAssumedRole
      - run: npm ci && cd dummy-frontend && npm ci
      - name: CDK deploy
        run: npx cdk deploy --context prefix=${UNIQUE_PREFIX} --context google-client-id=${GOOGLE_CLIENT_ID} --context google-client-secret=${GOOGLE_CLIENT_SECRET}
        env:
          UNIQUE_PREFIX: ${{ secrets.UNIQUE_PREFIX }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
